version: '3.8'

services:
  chatbot-persional-one:
    image: chatbot-persional-one
    build: .
    ports:
      - "5050:5000"
      - "443:5000"
    restart: unless-stopped
    volumes:
      - .:/app  # Chỉ dùng khi dev, nếu production nên bỏ
    environment:
      - PYTHONUNBUFFERED=1
    # depends_on:
    #   - qwen3vl-server

# volumes:
#   ollama-data-gpu-zero:
  # ollama-data-gpu1:
