version: '3.8'

services:
  # ollama-gpu-zero:
  #   image: ollama/ollama
  #   container_name: ollama-gpu-zero
  #   restart: unless-stopped
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - D:\ollama:/root/.ollama
  #   environment:
  #     - OLLAMA_MAX_LOADED_MODELS=2
  #     - OLLAMA_NUM_PARALLEL=4
  #     - OLLAMA_MAX_QUEUE=512
  #     - NVIDIA_VISIBLE_DEVICES=all # Sử dụng tất cả các GPU
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]
  #   runtime: nvidia


  chatbot-persional-one:
    image: chatbot-persional-one
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - C:\Users\ADMIN\Downloads\blackbox:/app  # Chỉ dùng khi dev, nếu production nên bỏ
    environment:
      - PYTHONUNBUFFERED=1
    # depends_on:
    #   - qwen3vl-server

  qwen3vl-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda-b7717
    container_name: qwen3vl-server
    ports:
      - "8070:8070"
    restart: unless-stopped
    volumes:
      - C:\Users\ADMIN\Downloads\blackbox\weights:/models
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    runtime: nvidia
    command: >
      -m models/Qwen3VL-8B-Instruct-Q4_K_M.gguf
      -c 5000
      --host 0.0.0.0
      --port 8070
      --n-gpu-layers 36
      --jinja
      --mmproj models/mmproj-Qwen3VL-8B-Instruct-Q8_0.gguf
      --parallel 1
      -b 4096
      -ub 4096

# volumes:
#   ollama-data-gpu-zero:
  # ollama-data-gpu1:
