[project]
name = "abox"
version = "0.1.0"
description = "Đây là một dự án Bot "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "crawl4ai>=0.9.1",
    "discord-py>=2.7.1",
    "fastapi>=0.115.0",
    "google-api-python-client>=2.198.0",
    "google-auth-httplib2>=0.4.0",
    "google-auth-oauthlib>=1.4.0",
    "google-genai>=2.11.0",
    "pandas>=3.0.3",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.2",
    "pytz>=2026.2",
    "requests>=2.34.2",
    "sympy>=1.14.0",
    "uvicorn[standard]>=0.34.0",
    "websockets>=14.0",
    "youtube-search>=2.2.0",
]

[tool.uv]
link-mode = "copy"
